### ISSUE TITLE
just a question

### ISSUE THREAD

**Issue by pharrowboy** [JeffMv/Lofea#3]
so i have a pretty firm belief that a lottery from where i am is affected by universe over 10, even though its a 649 lottery. each number in the draw has a "likely follower from a list of 18 or 21 numbers between 1 and 49" i was able to prove this by building a python script. 
and i discovered it was effectively making each of the 6 numbers drawn an embedded  1/49 lottery similiar to youre 1/10 lottery triomagic. 

upon testing your software Lofea, i have been able to correctly predict 2/6 number in the past 6 draws by manually reading a classification report generated by lofea. and i believe this because ussually the first 2 numbers of every draw are a number between 1 and 10 or 1 and 20. in order to predict numbers in the higher range i feel  i'd need to modify your code. but i'm having trouble understanding your code. 

i was wondering if you'd be willing to provide guidance on where in your code i should make edits to ensure it works for a 1/49 lottery.

**Comment by JeffMv** [comment]
Thanks for reaching out.
A simple trick you could use. The idea you could do without touching the code is the following:
- write a script that will convert the ball numbers [1-49] into bins of equal sizes (for instance 7 numbers in each bin) of so that the "universe" of the file you provide to the script becomes (in my example) [1-9].
- That means if you made bin 1 contain numbers {1,2,3,4,5,6,7} and bin 2 {8,9,10,11,12,13,14}, then when the script shows favor towards 1 and 2, you know it means the favored numbers are 1,2,3,4,...,12,13,14.
- You can choose which numbers you put in the bins, but beware that it's best to start with bins that have equiprobability. Only after you master this can you try with other types of bins.

Regards

**Comment by pharrowboy** [comment]
thank you, i value your guidance, i will have to give that a try
